package com.maskiproj.form;

import com.maskiproj.main.Main;
import com.maskiproj.model.Material;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 * @author fauzi afnan13579@gmail.com
 */
public class Formula extends javax.swing.JFrame {

    private int id = 0;
    private final Main main;
    private final Material material;

    /**
     * Creates new form Formula
     *
     * @param main
     */
    public Formula(Main main) {
        this.main = main;
        this.material = main.getModelMaterial();

        initComponents();
        initSelectionListener();

        loadMaterial();
    }

    private void initSelectionListener() {
        tbFormula.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                int rowNumber = tbFormula.getSelectedRow();
                if (rowNumber >= 0) {
                    String nama = tbFormula.getValueAt(rowNumber, 0).toString();
                    String formula = tbFormula.getValueAt(rowNumber, 1).toString();
                    this.id = material.getMaterialId(nama, formula);

                    tfMaterial.setText(nama);
                    tfFormula.setText(formula);
                    rbEdit.setSelected(true);
                }
            }
        });
    }

    private void loadMaterial() {
        DefaultTableModel modelMaterial = new DefaultTableModel(null, Material.MATERIAL_COLUMN_TITLE);
        modelMaterial.setRowCount(0);

        String[][] listMaterial = material.getListMaterial();
        for (String[] row : listMaterial) {
            modelMaterial.addRow(row);
        }

        tbFormula.setModel(modelMaterial);
    }

    private void clearInput() {
        tfFormula.setText("");
        tfMaterial.setText("");
        bgModeInput.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgModeInput = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbBaru = new javax.swing.JRadioButton();
        rbEdit = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFormula = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tfMaterial = new javax.swing.JTextField();
        tfFormula = new javax.swing.JTextField();
        btSelesai = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        jLabel2.setText("Mode Input");

        jLabel3.setText("Material");

        rbBaru.setBackground(new java.awt.Color(153, 153, 0));
        bgModeInput.add(rbBaru);
        rbBaru.setText("Baru");

        rbEdit.setBackground(new java.awt.Color(153, 153, 0));
        bgModeInput.add(rbEdit);
        rbEdit.setText("Edit");

        jScrollPane1.setViewportView(tbFormula);

        jLabel4.setText("Formula");

        btSelesai.setText("Selesai");
        btSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbBaru)
                        .addGap(18, 18, 18)
                        .addComponent(rbEdit))
                    .addComponent(btSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFormula)
                    .addComponent(tfMaterial))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbBaru)
                            .addComponent(rbEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btSelesai))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("MASKI MAGIC TOOLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Form");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelesaiActionPerformed
        String nama = tfMaterial.getText().trim();
        int formula = 0;
        if (tfFormula.getText().contains("*")) {
            try {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine engine = mgr.getEngineByName("JavaScript");
                String foo = tfFormula.getText().trim();
                formula = Integer.parseInt(engine.eval(foo).toString());
            } catch (ScriptException ex) {
                Logger.getLogger(Formula.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            formula = Integer.parseInt(tfFormula.getText().trim());
        }
        //// New, Edit, or no-select
        if (rbBaru.isSelected()) {
            if (material.insertMaterial(nama, formula)) {
                JOptionPane.showMessageDialog(rootPane, "Data Material berhasil ditambahkan", "Info", JOptionPane.INFORMATION_MESSAGE);
                loadMaterial();
                clearInput();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data Material gagal ditambahkan", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (rbEdit.isSelected()) {
            if (material.updateMaterial(id, nama, formula)) {
                JOptionPane.showMessageDialog(rootPane, "Data Material berhasil diubah", "Info", JOptionPane.INFORMATION_MESSAGE);
                loadMaterial();
                clearInput();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data Material gagal diubah", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pilih mode terlebih dahulu: [Baru] atau [Edit]");
        }
    }//GEN-LAST:event_btSelesaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgModeInput;
    private javax.swing.JButton btSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBaru;
    private javax.swing.JRadioButton rbEdit;
    private javax.swing.JTable tbFormula;
    private javax.swing.JTextField tfFormula;
    private javax.swing.JTextField tfMaterial;
    // End of variables declaration//GEN-END:variables
}
