package com.maskiproj.form;

import com.maskiproj.main.Main;
import com.maskiproj.model.Material;
import com.maskiproj.model.Transaksi;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author fauzi afnan13579@gmail.com
 */
public class Kalkulator extends javax.swing.JFrame {

    private final Main main;
    private final Material material;
    private final Transaksi transaksi;

    private final DefaultTableModel modelTransaksi;
    private final NumberFormat format;

    /**
     * Creates new form Kalkulator
     *
     * @param main
     */
    public Kalkulator(Main main) {
        this.main = main;
        this.material = main.getModelMaterial();
        this.transaksi = main.getModelTransaksi();

        initComponents();

        format = NumberFormat.getInstance();
        modelTransaksi = new DefaultTableModel(null, Transaksi.TRANSAKSI_DETAIL_COLUMN_TITLE);
        tbTransaksi.setModel(modelTransaksi);

        loadMaterial();
    }

    private void loadMaterial() {
        cbMaterial.removeAllItems();
        String[][] dataMaterial = material.getListMaterial();
        for (String[] row : dataMaterial) {
            cbMaterial.addItem(row[0]);
        }
    }

    private void clearLeftInput() {
        cbMaterial.setSelectedIndex(0);
        tfPanjang.setText("");
        tfLebar.setText("");
        tfHarga.setText("");
    }

    private void clearRightInput() {
        tfPemesan.setText("");
        tfJenisPesanan.setText("");
        modelTransaksi.setRowCount(0);
        lbGrandTotal.setText("0");
    }

    private void calcGrandTotal() {
        try {
            int totalRow = modelTransaksi.getRowCount();
            double grandTotal = 0;
            for (int i = 0; i < totalRow; i++) {
                String sTotal = modelTransaksi.getValueAt(i, 3).toString();
                grandTotal += format.parse(sTotal).doubleValue();
            }
            lbGrandTotal.setText(String.format("%.2f", grandTotal));
        } catch (ParseException ex) {
            Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPanjang = new javax.swing.JTextField();
        tfLebar = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        cbMaterial = new javax.swing.JComboBox<>();
        btHitung = new javax.swing.JButton();
        btDeleteItem = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTransaksi = new javax.swing.JTable();
        btSelesai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfAddons = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfHargaTambahan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbGrandTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfJenisPesanan = new javax.swing.JTextField();
        tfPemesan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miFormula = new javax.swing.JMenuItem();
        miLaporan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miKeluar = new javax.swing.JMenuItem();

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("MASKI MAGIC TOOLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Bahan");

        jLabel3.setText("Panjang");

        jLabel4.setText("Lebar");

        jLabel5.setText("Harga");

        tfPanjang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPanjang.setName("inputpanjang"); // NOI18N
        tfPanjang.setNextFocusableComponent(tfLebar);

        tfLebar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfLebar.setName("inputlebar"); // NOI18N
        tfLebar.setNextFocusableComponent(tfHarga);

        tfHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfHarga.setName("inputharga"); // NOI18N
        tfHarga.setNextFocusableComponent(btHitung);

        cbMaterial.setNextFocusableComponent(tfPanjang);

        btHitung.setText("Hitung");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });

        btDeleteItem.setForeground(new java.awt.Color(255, 51, 51));
        btDeleteItem.setText("Hapus Item");
        btDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteItemActionPerformed(evt);
            }
        });

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAdd.setText("+");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tbTransaksi);

        btSelesai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btSelesai.setForeground(new java.awt.Color(0, 102, 0));
        btSelesai.setText("Selesai");
        btSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelesaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Add-ons");

        tfAddons.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfAddons.setNextFocusableComponent(tfHargaTambahan);

        jLabel7.setText("Harga");

        tfHargaTambahan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfHargaTambahan.setNextFocusableComponent(btAdd);
        tfHargaTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaTambahanActionPerformed(evt);
            }
        });

        jLabel8.setText("TOTAL");

        lbGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGrandTotal.setText("0");

        jLabel10.setText("Pemesan");

        jLabel12.setText("Jenis pesanan");

        tfJenisPesanan.setNextFocusableComponent(btSelesai);

        tfPemesan.setNextFocusableComponent(tfJenisPesanan);

        jLabel13.setText("m");

        jLabel14.setText("m");

        jLabel15.setText("Rupiah");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(tfLebar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHarga, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))))
                    .addComponent(btHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfHargaTambahan, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(tfAddons))))
                        .addGap(18, 18, 18)
                        .addComponent(btAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btDeleteItem, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(tfJenisPesanan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfJenisPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addComponent(btHitung))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfAddons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfHargaTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdd))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btDeleteItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)
                                .addComponent(lbGrandTotal))
                            .addComponent(btSelesai, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        jMenu1.setText("Form");

        miFormula.setText("Formula");
        miFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormulaActionPerformed(evt);
            }
        });
        jMenu1.add(miFormula);

        miLaporan.setText("Laporan");
        miLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLaporanActionPerformed(evt);
            }
        });
        jMenu1.add(miLaporan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        miKeluar.setText("Keluar");
        miKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKeluarActionPerformed(evt);
            }
        });
        jMenu2.add(miKeluar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // get formula from database
        int id = material.getMaterialId(cbMaterial.getSelectedItem().toString());
        int formula = material.getFormulaById(id);

        // siapkan angka input
        double panjang = Double.parseDouble(tfPanjang.getText());
        double lebar = Double.parseDouble(tfLebar.getText());
        double harga = Double.parseDouble(tfHarga.getText());

        // perhitungan
        double luas = panjang * lebar;
        double hasil = luas / formula;
        double subtotal = hasil * harga;

        // add to table
        String[] rowData = new String[4];
        rowData[0] = cbMaterial.getSelectedItem().toString();
        rowData[1] = String.format("%.0f", luas);
        rowData[2] = String.format("%.4f", hasil);
        rowData[3] = String.format("%.2f", subtotal);
        modelTransaksi.addRow(rowData);

        // calc total
        calcGrandTotal();

        // clear input
        clearLeftInput();
    }//GEN-LAST:event_btHitungActionPerformed

    private void btDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteItemActionPerformed
        // hapus barang terpilih
        if (tbTransaksi.getSelectedRow() > -1) {
            int selectedRow = tbTransaksi.getSelectedRow();
            modelTransaksi.removeRow(selectedRow);
        }

        // hitung total
        calcGrandTotal();
    }//GEN-LAST:event_btDeleteItemActionPerformed

    private void btSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelesaiActionPerformed
        // populate input
        String pemesan = tfPemesan.getText().trim();
        String jenisPesanan = tfJenisPesanan.getText().trim();
        int itemCount = modelTransaksi.getRowCount();
        double total = 0;
        try {
            total = format.parse(lbGrandTotal.getText()).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
        }

        // validation
        if (pemesan.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Pemesan masih kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jenisPesanan.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Jenis pesanan masih kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (itemCount == 0) {
            JOptionPane.showMessageDialog(rootPane, "Item pesanan masih kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // populate table item
        String[][] detail = new String[itemCount][4];
        for (int i = 0; i < itemCount; i++) {
            detail[i][0] = tbTransaksi.getValueAt(i, 0).toString();
            detail[i][1] = tbTransaksi.getValueAt(i, 1).toString();
            detail[i][2] = tbTransaksi.getValueAt(i, 2).toString();
            detail[i][3] = tbTransaksi.getValueAt(i, 3).toString();
        }

        // insert to database
        if (transaksi.insertTransaksi(pemesan, jenisPesanan, total, detail)) {
            JOptionPane.showMessageDialog(rootPane, "Data transaksi berhasil dimasukkan", "Info", JOptionPane.INFORMATION_MESSAGE);
            clearRightInput();
            cbMaterial.requestFocus();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data transaksi gagal dimasukkan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSelesaiActionPerformed

    private void tfHargaTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaTambahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaTambahanActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // add to table
        String[] rowData = new String[4];
        rowData[0] = "Addons: " + tfAddons.getText().trim();
        rowData[1] = "0";
        rowData[2] = "0";
        rowData[3] = tfHargaTambahan.getText().trim();
        modelTransaksi.addRow(rowData);

        // calc total
        calcGrandTotal();

        // clear input
        clearLeftInput();
    }//GEN-LAST:event_btAddActionPerformed

    private void miKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKeluarActionPerformed
        main.exit();
    }//GEN-LAST:event_miKeluarActionPerformed

    private void miFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormulaActionPerformed
        main.hideKalkulator();
        main.showFormula();
    }//GEN-LAST:event_miFormulaActionPerformed

    private void miLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLaporanActionPerformed
        main.hideKalkulator();
        main.showLaporan();
    }//GEN-LAST:event_miLaporanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDeleteItem;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btSelesai;
    private javax.swing.JComboBox<String> cbMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGrandTotal;
    private javax.swing.JMenuItem miFormula;
    private javax.swing.JMenuItem miKeluar;
    private javax.swing.JMenuItem miLaporan;
    private javax.swing.JTable tbTransaksi;
    private javax.swing.JTextField tfAddons;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfHargaTambahan;
    private javax.swing.JTextField tfJenisPesanan;
    private javax.swing.JTextField tfLebar;
    private javax.swing.JTextField tfPanjang;
    private javax.swing.JTextField tfPemesan;
    // End of variables declaration//GEN-END:variables
}
